# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x0bmedical_rag\"x\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12&\n\x08messages\x18\x02 \x03(\x0b\x32\x14.medical_rag.Message\x12-\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x1d.medical_rag.GenerationConfig\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"J\n\x10GenerationConfig\x12\x12\n\nmax_tokens\x18\x01 \x01(\x05\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\r\n\x05top_p\x18\x03 \x01(\x02\"2\n\x0c\x43hatResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x13\n\x0bis_finished\x18\x02 \x01(\x08\x32_\n\x12MedicalChatService\x12I\n\x0eGenerateStream\x12\x18.medical_rag.ChatRequest\x1a\x19.medical_rag.ChatResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=26
  _globals['_CHATREQUEST']._serialized_end=146
  _globals['_MESSAGE']._serialized_start=148
  _globals['_MESSAGE']._serialized_end=188
  _globals['_GENERATIONCONFIG']._serialized_start=190
  _globals['_GENERATIONCONFIG']._serialized_end=264
  _globals['_CHATRESPONSE']._serialized_start=266
  _globals['_CHATRESPONSE']._serialized_end=316
  _globals['_MEDICALCHATSERVICE']._serialized_start=318
  _globals['_MEDICALCHATSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
